### ISSUE TITLE
Metrologia 6 3 69 is crashing

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#35]
````
[relaton-bipm] ("BIPM Metrologia 6 3 69") found Metrologia 6 3 69
bundler: failed to load command: relaton (/Users/nickn/.rbenv/versions/3.1.2/bin/relaton)
/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:25:in `encode': "\\xC2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:25:in `prepare'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:19:in `encode'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/htmlentities-4.3.4/lib/htmlentities.rb:73:in `encode'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.5/lib/relaton_bib/localized_string.rb:90:in `escp'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.5/lib/relaton_bib/formatted_string.rb:43:in `encode'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.5/lib/relaton_bib/localized_string.rb:67:in `to_xml'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.5/lib/relaton_bib/formatted_string.rb:31:in `to_xml'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.5/lib/relaton_bib/bibliographic_item.rb:760:in `block (3 levels) in render_xml'
````

**Comment by andrew2net** [comment]
fixed in relaton-bib v1.13.6
