### ISSUE TITLE
(URGENT) Crash in fetching BIPM items

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#45]
From https://github.com/metanorma/bipm-si-brochure

```
[relaton-bipm] ("CGPM Resolution 1901-01") fetching...
[relaton-bipm] ("CGPM Resolution 1901-02") fetching...
[relaton-bipm] ("CGPM Resolution 1927-01") fetching...
[relaton-bipm] ("CGPM Resolution 1948-03") fetching...
[relaton-bipm] ("CGPM Resolution 1948-06") fetching...
[relaton-bipm] ("CGPM Resolution 1889-00") fetching...
[relaton-bipm] ("CGPM Meeting 9") fetching...
[relaton] ERROR: CGPM Resolution 1948-06 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Resolution 1948-03 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Resolution 1889-00 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Resolution 1901-01 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Resolution 1927-01 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Meeting 9 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Resolution 1901-02 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1948-01") fetching...
[relaton] ERROR: CGPM Resolution 1948-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1954-03") fetching...
[relaton] ERROR: CGPM Resolution 1954-03 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1954-04") fetching...
[relaton] ERROR: CGPM Resolution 1954-04 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1954-06") fetching...
[relaton] ERROR: CGPM Resolution 1954-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1960-06") fetching...
[relaton] ERROR: CGPM Resolution 1960-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1960-09") fetching...
[relaton] ERROR: CGPM Resolution 1960-09 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1960-12") fetching...
[relaton] ERROR: CGPM Resolution 1960-12 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1960-13") fetching...
[relaton] ERROR: CGPM Resolution 1960-13 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1964-05") fetching...
[relaton] ERROR: CGPM Resolution 1964-05 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1964-06") fetching...
[relaton] ERROR: CGPM Resolution 1964-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1964-07") fetching...
[relaton] ERROR: CGPM Resolution 1964-07 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1964-08") fetching...
[relaton] ERROR: CGPM Resolution 1964-08 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1983-01") fetching...
[relaton] ERROR: CGPM Resolution 1983-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1991-04") fetching...
[relaton] ERROR: CGPM Resolution 1991-04 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1983-02") fetching...
[relaton] ERROR: CGPM Resolution 1983-02 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1979-03") fetching...
[relaton] ERROR: CGPM Resolution 1979-03 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1979-05") fetching...
[relaton] ERROR: CGPM Resolution 1979-05 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1979-06") fetching...
[relaton] ERROR: CGPM Resolution 1979-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1987-06") fetching...
[relaton] ERROR: CGPM Resolution 1987-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-01") fetching...
[relaton] ERROR: CGPM Resolution 1967-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1975-02") fetching...
[relaton] ERROR: CGPM Resolution 1975-02 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1975-08") fetching...
[relaton] ERROR: CGPM Resolution 1975-08 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Meeting 14") fetching...
[relaton] ERROR: CGPM Meeting 14 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1975-09") fetching...
[relaton] ERROR: CGPM Resolution 1975-09 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1971-02") fetching...
[relaton] ERROR: CGPM Resolution 1971-02 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-05") fetching...
[relaton] ERROR: CGPM Resolution 1967-05 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1971-01") fetching...
[relaton] ERROR: CGPM Resolution 1971-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1975-10") fetching...
[relaton] ERROR: CGPM Resolution 1975-10 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-06") fetching...
[relaton] ERROR: CGPM Resolution 1967-06 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-07") fetching...
[relaton] ERROR: CGPM Resolution 1967-07 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1995-08") fetching...
[relaton] ERROR: CGPM Resolution 1995-08 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1999-07") fetching...
[relaton] ERROR: CGPM Resolution 1999-07 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1999-12") fetching...
[relaton] ERROR: CGPM Resolution 1999-12 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2003-10") fetching...
[relaton] ERROR: CGPM Resolution 2003-10 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2007-09") fetching...
[relaton] ERROR: CGPM Resolution 2007-09 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2007-10") fetching...
[relaton] ERROR: CGPM Resolution 2007-10 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2007-12") fetching...
[relaton] ERROR: CGPM Resolution 2007-12 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2014-01") fetching...
[relaton] ERROR: CGPM Resolution 2014-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2011-01") fetching...
[relaton] ERROR: CGPM Resolution 2011-01 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Resolution (1879)") fetching...
[relaton] ERROR: CIPM Resolution (1879) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1948-07") fetching...
[relaton] ERROR: CGPM Resolution 1948-07 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1948-02") fetching...
[relaton] ERROR: CGPM Resolution 1948-02 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 2011-08") fetching...
[relaton] ERROR: CGPM Resolution 2011-08 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-03") fetching...
[relaton] ERROR: CGPM Resolution 1967-03 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1967-04") fetching...
[relaton] ERROR: CGPM Resolution 1967-04 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1971-03") fetching...
[relaton] ERROR: CGPM Resolution 1971-03 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1948-05") fetching...
[relaton] ERROR: CGPM Resolution 1948-05 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Resolution 1975-05") fetching...
[relaton-bipm] ("CGPM Declaration 1971-00") fetching...
[relaton] ERROR: CGPM Resolution 1975-05 -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CGPM Declaration 1971-00 -- no implicit conversion of Symbol into Integer
[relaton] si-brochure-fr does not have a recognised prefix
[relaton-bipm] ("CIPM Meeting 41") fetching...
[relaton-bipm] ("CIPM Resolution 1 (1946)") fetching...
[relaton] ERROR: CIPM Resolution 1 (1946) -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CIPM Meeting 41 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Resolution 2 (1946)") fetching...
[relaton] ERROR: CIPM Resolution 2 (1946) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Resolution (1948)") fetching...
[relaton] ERROR: CIPM Resolution (1948) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Resolution 1 (1956)") fetching...
[relaton] ERROR: CIPM Resolution 1 (1956) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Resolution 3 (1956)") fetching...
[relaton] ERROR: CIPM Resolution 3 (1956) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation (1961)") fetching...
[relaton] ERROR: CIPM Recommendation (1961) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Declaration (1964)") fetching...
[relaton] ERROR: CIPM Declaration (1964) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (1967)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (1967) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (1969)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (1969) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CCTF Recommendation 2 (1970)") fetching...
[relaton] ERROR: CCTF Recommendation 2 (1970) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (1980)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (1980) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (1984)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (1984) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (1988)") fetching...
[relaton-bipm] ("CIPM Recommendation 1 (1988)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (1988) -- no implicit conversion of Symbol into Integer
[relaton] ERROR: CIPM Recommendation 1 (1988) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 5 (1989)") fetching...
[relaton] ERROR: CIPM Recommendation 5 (1989) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Declaration (2001)") fetching...
[relaton] ERROR: CIPM Declaration (2001) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (2002)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (2002) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (2002)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (2002) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (2003)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (2003) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (2005)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (2005) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 3 (2005)") fetching...
[relaton] ERROR: CIPM Recommendation 3 (2005) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (2006)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (2006) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (2007)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (2007) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (2009)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (2009) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 1 (2013)") fetching...
[relaton] ERROR: CIPM Recommendation 1 (2013) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Recommendation 2 (2015)") fetching...
[relaton] ERROR: CIPM Recommendation 2 (2015) -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Decision 2017-10") fetching...
[relaton] ERROR: CIPM Decision 2017-10 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Meeting 43") fetching...
[relaton] ERROR: CIPM Meeting 43 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Meeting 51") fetching...
[relaton] ERROR: CIPM Meeting 51 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CIPM Meeting 4") fetching...
[relaton] ERROR: CIPM Meeting 4 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("CGPM Meeting 11") fetching...
[relaton] ERROR: CGPM Meeting 11 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 7 1 43") fetching...
[relaton] ERROR: BIPM Metrologia 7 1 43 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 26 1 69") fetching...
[relaton] ERROR: BIPM Metrologia 26 1 69 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 27 1 11") fetching...
[relaton] ERROR: BIPM Metrologia 27 1 11 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 29 1 1") fetching...
[relaton] ERROR: BIPM Metrologia 29 1 1 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 33 1 81") fetching...
[relaton] ERROR: BIPM Metrologia 33 1 81 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 34 3 261") fetching...
[relaton] ERROR: BIPM Metrologia 34 3 261 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 37 1 87") fetching...
[relaton] ERROR: BIPM Metrologia 37 1 87 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 40 2 103") fetching...
[relaton] ERROR: BIPM Metrologia 40 2 103 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 41 1 99") fetching...
[relaton] ERROR: BIPM Metrologia 41 1 99 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 43 1 175") fetching...
[relaton] ERROR: BIPM Metrologia 43 1 175 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 44 1 97") fetching...
[relaton] ERROR: BIPM Metrologia 44 1 97 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 52 1 155") fetching...
[relaton] ERROR: BIPM Metrologia 52 1 155 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 56 2 022001") fetching...
[relaton] ERROR: BIPM Metrologia 56 2 022001 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 4 1 41") fetching...
[relaton] ERROR: BIPM Metrologia 4 1 41 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 8 1 32") fetching...
[relaton] ERROR: BIPM Metrologia 8 1 32 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 16 1 55") fetching...
[relaton] ERROR: BIPM Metrologia 16 1 55 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 20 1 25") fetching...
[relaton] ERROR: BIPM Metrologia 20 1 25 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 25 2 113") fetching...
[relaton] ERROR: BIPM Metrologia 25 2 113 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 11 4 179") fetching...
[relaton] ERROR: BIPM Metrologia 11 4 179 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 21 2 89") fetching...
[relaton] ERROR: BIPM Metrologia 21 2 89 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 17 2 69") fetching...
[relaton] ERROR: BIPM Metrologia 17 2 69 -- no implicit conversion of Symbol into Integer
[relaton-bipm] ("BIPM Metrologia 6 2 65") fetching...
[relaton] ERROR: BIPM Metrologia 6 2 65 -- no implicit conversion of Symbol into Integer
```

Fetching a single item already fails:

```sh
$ bundle exec relaton fetch "CGPM Resolution 1889-00"
[relaton-bipm] ("CGPM Resolution 1889-00") fetching...
bundler: failed to load command: relaton (/Users/me/.asdf/installs/ruby/3.1.2/bin/relaton)
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:48:in `block in get_bipm': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.5/lib/relaton/index/type.rb:51:in `block in search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.5/lib/relaton/index/type.rb:50:in `select'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.5/lib/relaton/index/type.rb:50:in `search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:48:in `get_bipm'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:13:in `search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:70:in `get'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/processor.rb:20:in `get'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:187:in `fetch_doc'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:469:in `net_retry'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:438:in `new_bib_entry'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:402:in `check_bibliocache'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:64:in `fetch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-cli-1.15.2/lib/relaton/cli/command.rb:183:in `fetch_document'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-cli-1.15.2/lib/relaton/cli/command.rb:31:in `fetch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `block in run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hollaback-0.1.1/lib/hollaback/sequence.rb:34:in `call'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-cli-1.15.2/lib/relaton/cli.rb:41:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-cli-1.15.2/exe/relaton:20:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/relaton:25:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/relaton:25:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli.rb:492:in `exec'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/cli.rb:28:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/exe/bundle:45:in `block in <top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.11/exe/bundle:33:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by ronaldtse** [comment]
For every relaton-data-* update, we must run relaton-* tests to ensure they pass.

**Comment by ronaldtse** [comment]
@andrew2net I'm not sure if this is really an update issue. The fetches are still all failing:

```sh
$ bundle exec relaton fetch "CGPM Resolution 1901-01"
[relaton-bipm] ("CGPM Resolution 1901-01") fetching...
bundler: failed to load command: relaton (/Users/me/.asdf/installs/ruby/3.1.2/bin/relaton)
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:48:in `block in get_bipm': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.6/lib/relaton/index/type.rb:61:in `block in search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.6/lib/relaton/index/type.rb:60:in `select'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-index-0.1.6/lib/relaton/index/type.rb:60:in `search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:48:in `get_bipm'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:13:in `search'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/bipm_bibliography.rb:70:in `get'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bipm-1.14.3/lib/relaton_bipm/processor.rb:20:in `get'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-1.15.1/lib/relaton/db.rb:187:in `fetch_doc'
```

**Comment by andrew2net** [comment]
@ronaldtse hmm... I don't get the error. Can you show me a part of `~/.relaton/bipm/index.yaml`?
Please try to remove the `~/.relaton/bipm/index.yaml` and fetch again.

**Comment by ronaldtse** [comment]
After removing `~/.relaton/bipm/index.yaml`, fetching worked.

Here's the index.yaml file: [index.yaml.zip](https://github.com/relaton/relaton-bipm/files/11240296/index.yaml.zip)

In any case we have the following two follow up tasks:
* [ ] If Relaton gem sees any load error or yaml error in the cached index (or any cached documents), it should consider the cache as corrupt and wipe it
* [ ] `db clear` command should wipe the cached index

Thanks!
